module.exports={
    HOST:'sql12.freesqldatabase.com',
    USER:'',
    PASSWORD:'',
    DB:'',
    PORT:3306,
    dialect:'mysql',
    pool:{
        max:5,
        min:0,
        acquire:30000,
        idle:10000
    }
}